# Generated by Django 5.2.7 on 2026-01-20 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('FRONT', 'Front-end'), ('BACK', 'Back-end')], max_length=10)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(blank=True, null=True, upload_to='galaxias/')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor_tema', models.CharField(default='#FFFFFF', max_length=7)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='planetas/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('galaxia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planetas', to='universe.galaxia')),
            ],
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='universe.planeta')),
            ],
        ),
    ]
