# Generated by Django 5.2.7 on 2026-01-20 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoria'), ('QUIZ', 'Exercício')], max_length=10)),
                ('conteudo_teorico', models.TextField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='universe.missao')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('explicacao_erro', models.TextField(help_text='Texto para o feedback de erro')),
                ('explicacao_acerto', models.TextField(help_text='Texto para o feedback de acerto')),
                ('atividade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questao', to='activity.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('is_correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='activity.questao')),
            ],
        ),
    ]
